# workflow to build and push docker image to AWS ECR (Elastic Container Registory)

name: CI-CD-flask-pipeline

on:
  workflow_dispatch:
env:
 ECR_REPOSITORY: flask_app_ecr
 IMAGE_TAG: ${{ github.sha }}
 AWS_REGION: us-west-2

#Jobs to build, configure and push 
jobs:
  Deployment:
    name: CI-CD of flask application
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Get ECR repository URI
    # ecr_repository_url = "678499129427.dkr.ecr.us-west-2.amazonaws.com/flask_app_ecr"
      id: get_ecr_uri
      run: |
        ECR_REPOSITORY_URI=$(aws ecr describe-repositories --repository-names $ECR_REPOSITORY --query 'repositories[0].repositoryUri' --output text)
        echo "ECR_REPOSITORY_URI=$ECR_REPOSITORY_URI" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Configure Docker Client
      run: |-
         gcloud auth configure-docker --quiet
         gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: docker version command
      run: docker --version

    - name: build, tag and push image to ECR
#        IMAGE_TAG: flask_app
      run: |
        docker build -t ${{ env.ECR_REPOSITORY_URI }}:$IMAGE_TAG ./app
        docker ps -a 
        docker push ${{ env.ECR_REPOSITORY_URI }}:$IMAGE_TAG
#        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app
     #   docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    # - name: Deploy to EKS
    #   run: |
    #     COMMIT_SHA=${{ github.sha }}
    #     kubectl set image deployment/my-deployment my-container=${{ env.ECR_REPOSITORY_URI }}:$COMMIT_SHA --record
    #     kubectl rollout status deployment/my-deployment
    # - name: Deploy to EKS
    #   uses: aws-actions/amazon-eks-deploy@v2
    #   with:
    #     aws-region: ${{ env.AWS_REGION }}
    #     cluster-name: ${{ env.ECS_CLUSTER }}
    #     service-name: ${{ env.ECS_SERVICE }}
    #     container-name: ${{ env.CONTAINER_NAME }}
    #     container-port: 80
    #     image: ${{ steps.build-image.outputs.image }}






          
